"""
SOC Incident Response Playbook & Threat Containment Generator
Generates YARA rules, SIGMA SIEM hunting rules, STIX 2.1 bundles,
and automated containment playbooks for email security investigations.
"""

import json
import re
from datetime import datetime


def sanitize_identifier(text: str) -> str:
    """Convert arbitrary strings into valid YARA rule identifiers."""
    cleaned = re.sub(r'[^a-zA-Z0-9_]', '_', text)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"rule_{cleaned}"
    return cleaned[:40]


def generate_yara_rule(scan_data: dict) -> str:
    """Generate a valid YARA detection rule for the analyzed email threat."""
    subject = scan_data.get('subject', scan_data.get('email_subject', 'Suspicious Email'))
    rule_name = f"Email_Threat_{sanitize_identifier(subject)}"
    
    forensic = scan_data.get('forensic', {})
    routing = forensic.get('routing', {})
    origin_ip = routing.get('origin_ip', scan_data.get('geo', {}).get('ip', ''))
    
    from_header = scan_data.get('from', scan_data.get('sender', ''))
    brand_info = forensic.get('brand_impersonation', {})
    claimed_brand = brand_info.get('claimed_brand', '')
    
    urls = scan_data.get('urls_found', [])
    sample_url = urls[0] if urls else ''
    
    strings_list = []
    strings_list.append(f'        $subject = "{subject}" ascii wide nocase')
    if from_header:
        strings_list.append(f'        $sender = "{from_header}" ascii wide nocase')
    if origin_ip and origin_ip != 'Unknown':
        strings_list.append(f'        $origin_ip = "{origin_ip}" ascii')
    if sample_url:
        domain_part = sample_url.split('/')[2] if '/' in sample_url else sample_url
        strings_list.append(f'        $mal_url = "{domain_part}" ascii wide nocase')
    if claimed_brand:
        strings_list.append(f'        $brand_kw = "{claimed_brand}" ascii wide nocase')

    strings_block = "\n".join(strings_list) if strings_list else '        $default_kw = "phishing" ascii wide nocase'
    
    yara_code = f"""rule {rule_name} {{
    meta:
        description = "Autogenerated YARA rule for email threat detection"
        author = "MailForensic AI SOC Engine"
        date = "{datetime.utcnow().strftime('%Y-%m-%d')}"
        severity = "{scan_data.get('risk_assessment', {}).get('risk_level', 'High')}"
        reference = "Case MF-{datetime.utcnow().strftime('%Y%m%d')}"

    strings:
{strings_block}

    condition:
        2 of them
}}"""
    return yara_code


def generate_sigma_rule(scan_data: dict) -> str:
    """Generate a SIGMA SIEM hunting rule for Splunk, Sentinel, and Elastic."""
    subject = scan_data.get('subject', scan_data.get('email_subject', 'Suspicious Phishing Email'))
    forensic = scan_data.get('forensic', {})
    routing = forensic.get('routing', {})
    origin_ip = routing.get('origin_ip', scan_data.get('geo', {}).get('ip', '185.220.101.34'))
    sender = scan_data.get('from', 'security-alert@suspicious-domain.com')
    
    sigma_code = f"""title: Phishing Threat Detection - {subject[:50]}
id: {sanitize_identifier(subject)}-{datetime.utcnow().strftime('%Y%m%d')}
status: experimental
description: Detects suspicious email transit and header anomalies matching case investigation.
author: MailForensic AI SOC Engine
date: {datetime.utcnow().strftime('%Y/%m/%d')}
references:
    - https://attack.mitre.org/techniques/T1566/002/
logsource:
    category: email
    product: exchange
detection:
    selection_sender:
        Sender: '{sender}'
    selection_ip:
        OriginatingIP: '{origin_ip}'
    condition: selection_sender or selection_ip
falsepositives:
    - Legitimate internal communications with unconfigured SPF
level: {scan_data.get('risk_assessment', {}).get('risk_level', 'high').lower()}
tags:
    - attack.initial_access
    - attack.t1566.002
"""
    return sigma_code


def generate_stix_bundle(scan_data: dict) -> dict:
    """Generate STIX 2.1 Threat Intelligence JSON object."""
    forensic = scan_data.get('forensic', {})
    routing = forensic.get('routing', {})
    origin_ip = routing.get('origin_ip', scan_data.get('geo', {}).get('ip', '185.220.101.34'))
    sender = scan_data.get('from', 'unknown@suspicious-domain.com')
    subject = scan_data.get('subject', 'Phishing Campaign')
    
    stix_id = f"indicator--{sanitize_identifier(subject)}-{datetime.utcnow().strftime('%Y%m%d')}"
    
    return {
        "type": "bundle",
        "id": f"bundle--{stix_id}",
        "spec_version": "2.1",
        "objects": [
            {
                "type": "indicator",
                "spec_version": "2.1",
                "id": stix_id,
                "created": datetime.utcnow().isoformat() + "Z",
                "modified": datetime.utcnow().isoformat() + "Z",
                "name": f"Email Threat Indicator: {subject}",
                "description": "Auto-generated threat indicator from MailForensic AI Engine",
                "pattern": f"[ipv4-addr:value = '{origin_ip}' OR email-message:from_email_addrs.value = '{sender}']",
                "pattern_type": "stix",
                "valid_from": datetime.utcnow().isoformat() + "Z",
                "labels": ["malicious-activity", "phishing"]
            }
        ]
    }


def generate_soc_playbook(scan_data: dict) -> dict:
    """Full SOC Playbook response object."""
    forensic = scan_data.get('forensic', {})
    routing = forensic.get('routing', {})
    origin_ip = routing.get('origin_ip', scan_data.get('geo', {}).get('ip', '185.220.101.34'))
    from_header = scan_data.get('from', 'security-alert@suspicious-domain.com')
    domain = from_header.split('@')[-1] if '@' in from_header else 'suspicious-domain.com'
    
    risk = scan_data.get('risk_assessment', {})
    risk_level = risk.get('risk_level', 'High')

    actions = [
        {
            "id": "quarantine_email",
            "title": "Quarantine Email from Recipient Inboxes",
            "description": f"Issue automated API command to purge email with subject '{scan_data.get('subject', 'Threat Email')}' across Exchange/Gmail tenant.",
            "category": "Mailbox Remediation",
            "status": "Recommended",
            "command": f"Search-Mailbox -TargetMailbox 'Quarantine' -SearchQuery 'Subject:\"{scan_data.get('subject', '')}\"'"
        },
        {
            "id": "block_ip",
            "title": f"Block Origin IP ({origin_ip}) on Perimeter Firewall",
            "description": f"Add {origin_ip} to perimeter firewall and threat intelligence blocklist.",
            "category": "Network Defense",
            "status": "Recommended",
            "command": f"iptables -A INPUT -s {origin_ip} -j DROP"
        },
        {
            "id": "sinkhole_domain",
            "title": f"Sinkhole Spoofed Domain ({domain})",
            "description": "Reroute DNS lookups for spoofed domain to internal DNS sinkhole to block employee outbound clicks.",
            "category": "DNS Defense",
            "status": "Recommended",
            "command": f"zone \"{domain}\" {{ type master; file \"/etc/bind/db.sinkhole\"; }};"
        },
        {
            "id": "reset_credentials",
            "title": "Enforce Mandatory Password Reset & Revoke Active Sessions",
            "description": "Trigger automated OAuth token revocation and forced password reset for target employee account.",
            "category": "Identity Protection",
            "status": "Pending Analyst Signoff",
            "command": f"Revoke-AzureADUserAllRefreshToken -ObjectId {scan_data.get('to', 'target_user')}"
        }
    ]

    return {
        "case_id": forensic.get('evidence_id', f"CASE-MF-{datetime.utcnow().strftime('%Y%m%d')}"),
        "risk_level": risk_level,
        "actions": actions,
        "yara_rule": generate_yara_rule(scan_data),
        "sigma_rule": generate_sigma_rule(scan_data),
        "stix_bundle": generate_stix_bundle(scan_data)
    }
